python ../scimaf_dir.py --db ddf_pre_fn2_v1.7_10yrs.db
python ../scimaf_dir.py --db ddf_pre_fn1_v1.7_10yrs.db
python ../scimaf_dir.py --db ddf_pre_fn4_v1.7_10yrs.db
python ../scimaf_dir.py --db ddf_pre_fn0_v1.7_10yrs.db
python ../scimaf_dir.py --db ddf_pre_fn3_v1.7_10yrs.db
python ../glance_dir.py --db ddf_pre_fn2_v1.7_10yrs.db
python ../glance_dir.py --db ddf_pre_fn1_v1.7_10yrs.db
python ../glance_dir.py --db ddf_pre_fn4_v1.7_10yrs.db
python ../glance_dir.py --db ddf_pre_fn0_v1.7_10yrs.db
python ../glance_dir.py --db ddf_pre_fn3_v1.7_10yrs.db
